### ISSUE TITLE
Version numbers are a mess

### ISSUE THREAD

**Issue by jdemeyer** [miguelmarco/libhomfly#13]
The version number used by the autotools build system (hardcoded in `configure.ac` and seen by `./configure --version`) is `1.0r3` but the git repo has a tag `1.02r4`.

One consequence is that the name of the tarball hosted on GitHub is `libhomfly-1.02r4.tar.gz` but it extracts in a directory named `libhomfly-1.0r3`

**Comment by miguelmarco** [comment]
Fixed by making a new release with the correct version numbers (1.02r5)
